### ISSUE TITLE
Exception: No weights file found for element: O

### ISSUE THREAD

**Issue by ZengZezhu** [MarsalekGroup/aml#18]
Dear AML Team,

I just want to use the aml to generate a NNP potential of water. When I used the script of "create-model.py" prepared in the examples, I encountered an issue like below:

Traceback (most recent call last):
  File "/lustre1/u/u3004964/using_n2p2/aml-committee/water-cheng/create-model.py", line 35, in <module>
    n2p2.train(structures, n_epoch=2)
  File "/lustre1/u/u3004964/software/aml/aml/mlp.py", line 206, in train
    self._read_parameters(directories)
  File "/lustre1/u/u3004964/software/aml/aml/mlp.py", line 160, in _read_parameters
    model_parameters.append(self._read_output_train(directory))
  File "/lustre1/u/u3004964/software/aml/aml/mlp.py", line 449, in _read_output_train
    raise Exception(f'No weights file found for element: {element:s}')
Exception: No weights file found for element: O

I carefully prepared the input files (including input.data, input.nn and scaling,data) for training the NNP by using n2p2, and I also tested and found that it is correct if I directly run 'nnp-train' in the path of 'final-training/train-000'. Could you tell me what should I do for this issue? Many thanks. 

I am also confused about the aml function, does aml can be sued to train the NNP potential? or we need to use the n2p2 to train and then use the aml to generate the C-NNP? 

Cheers,
zezhu

**Comment by ZengZezhu** [comment]
Hi,

Now I solved this issue by a pre-fitting when performing the create-model.py, so I think that aml cannot be sued to fit the NNP. 

But I am still a little confused by the MD simulation of using C-NNP in lammps. I see that the final model just is a simple combination of 8 NNPs located on 8 different folders. Is it possible to use the final C-NNP model to perform MD simulations in lammps? Because I do not find the final C-NNP potential in the model folder, I don't know what should I do to average these 8 NNPs. I see the example of MD simulations in '04-C-NNP-MD' only gives the input of CP2K.:)
